Test wf
Signed-off-by: Simon Misencik <simon.misencik@gmail.com>

diff --git a/.github/workflows/frinx-machine-lint-test.yaml b/.github/workflows/frinx-machine-lint-test.yaml
--- a/.github/workflows/frinx-machine-lint-test.yaml
+++ b/.github/workflows/frinx-machine-lint-test.yaml
@@ -68,64 +68,71 @@ jobs:
           helm dependency update charts/frinx-machine
           helm upgrade $NAME charts/frinx-machine --set demo-workflows.enabled=true -n frinx-machine --wait --timeout 20m0s
 
+      - name: Port-forward UI
+        # id: port_forward
+        run: |
+          wget https://github.com/txn2/kubefwd/releases/download/1.22.5/kubefwd_Linux_x86_64.tar.gz
+          tar xzf kubefwd_Linux_x86_64.tar.gz
+          sudo ./kubefwd svc -n frinx-machine -f metadata.name=krakend
+
       # - name: Port-forward UI
       #   # id: port_forward
       #   run: |
       #     .github/script.sh 2>&1 | tee /home/runner/work/_temp/k8s-pod-forward.log &
 
-      - name: Setup Kubernetes port-forward daemon
-        uses: vbem/k8s-port-forward@v1
-        with:
-          workload: 'svc/krakend'
-          mappings: '8080:8080'
-          options: '--address=0.0.0.0 --namespace=frinx-machine'
+      # - name: Setup Kubernetes port-forward daemon
+      #   uses: vbem/k8s-port-forward@v1
+      #   with:
+      #     workload: 'svc/krakend'
+      #     mappings: '8080:8080'
+      #     options: '--address=0.0.0.0 --namespace=frinx-machine'
 
-      - name: Clone frinx-machine-e2e-tests
-        uses: actions/checkout@v3
-        with:
-          repository: FRINXio/frinx-machine-e2e-tests
-          ref: unify_test
-          token: ${{ secrets.TOKEN }}
-          path: './cypress'
+      # - name: Clone frinx-machine-e2e-tests
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: FRINXio/frinx-machine-e2e-tests
+      #     ref: unify_test
+      #     token: ${{ secrets.TOKEN }}
+      #     path: './cypress'
 
-      - name: Cypress tests
-        id: run_test
-        uses: cypress-io/github-action@v5
-        with:
-          spec: cypress/e2e/0-check-main-page/*,cypress/e2e/2-devices/*,cypress/e2e/3-workflow-builder/*,cypress/e2e/4-workflow-manager/*
-          working-directory: ./cypress
-        env:
-          CYPRESS_host: localhost:8080
+      # - name: Cypress tests
+      #   id: run_test
+      #   uses: cypress-io/github-action@v5
+      #   with:
+      #     spec: cypress/e2e/0-check-main-page/*,cypress/e2e/2-devices/*,cypress/e2e/3-workflow-builder/*,cypress/e2e/4-workflow-manager/*
+      #     working-directory: ./cypress
+      #   env:
+      #     CYPRESS_host: localhost:8080
 
-      - name: Show port-forward log
-        if: failure()
-        id: port_forward_log
-        run: |
-          cat /home/runner/work/_temp/k8s-pod-forward*
+      # - name: Show port-forward log
+      #   if: failure()
+      #   id: port_forward_log
+      #   run: |
+      #     cat /home/runner/work/_temp/k8s-pod-forward*
 
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: cypress-screenshots
-          path: ./cypress/cypress/screenshots
+      # - uses: actions/upload-artifact@v3
+      #   if: failure()
+      #   with:
+      #     name: cypress-screenshots
+      #     path: ./cypress/cypress/screenshots
 
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: cypress-videos
-          path: ./cypress/cypress/videos
+      # - uses: actions/upload-artifact@v3
+      #   if: failure()
+      #   with:
+      #     name: cypress-videos
+      #     path: ./cypress/cypress/videos
 
-      - name: Delete AKS cluster
-        if: ${{ ( success() || failure() || cancelled() ) &&  ( steps.create_aks_cluster.outcome != 'skipped' ) }}
-        run: |
-          az aks delete --resource-group github-e2e-tests --name aks-e2e-tests --yes
+      # - name: Delete AKS cluster
+      #   if: ${{ ( success() || failure() || cancelled() ) &&  ( steps.create_aks_cluster.outcome != 'skipped' ) }}
+      #   run: |
+      #     az aks delete --resource-group github-e2e-tests --name aks-e2e-tests --yes
 
-      - name: slack - GitHub Actions Slack integration
-        if: ${{ always() }}
-        uses: act10ns/slack@v2.0.0
-        with:
-          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
-          status: ${{ job.status }}
-          channel: '#fx_env_helm-charts'
-          message: "E2E tests: ${{ job.status }}\n${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nJob: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          steps: ${{ toJson(steps) }}
+      # - name: slack - GitHub Actions Slack integration
+      #   if: ${{ always() }}
+      #   uses: act10ns/slack@v2.0.0
+      #   with:
+      #     webhook-url: ${{ secrets.SLACK_WEBHOOK }}
+      #     status: ${{ job.status }}
+      #     channel: '#fx_env_helm-charts'
+      #     message: "E2E tests: ${{ job.status }}\n${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nJob: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      #     steps: ${{ toJson(steps) }}
